[package]
name = "pruebas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.23"
gpiod = "0.2.2"
i2c-linux = "0.1.2"
